spring:
  application:
    name: feignserver
server:
  port: 82

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1/eureka/
feign:
  hystrix:
    enabled: true